name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: '9.0.x'
  SOLUTION_PATH: 'Zenvestify.sln'

jobs:
  # Build Web
  build-web:
    name: Build Web App
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    
    - name: Build Web App
      run: dotnet build Zenvestify/Zenvestify.Web/Zenvestify.Web.csproj --configuration Release --no-restore
    
    - name: Publish Web App
      run: dotnet publish Zenvestify/Zenvestify.Web/Zenvestify.Web.csproj --configuration Release --output ./web-app
    
    - name: Upload web artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-app
        path: ./web-app